# Automatically updated by the winget bot at 2024/Nov/19
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: WestWind.MarkdownMonster
PackageVersion: 3.5.14.0
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
UpgradeBehavior: install
Commands:
- markdownmonster
- mm
- mmcli
FileExtensions:
- markdown
- md
- mdcrypt
- mdproj
- mkdown
ReleaseDate: 2024-12-10
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/RickStrahl/MarkdownMonsterReleases/raw/master/v3/v3.5/MarkdownMonsterSetup-3.5.14.exe
  InstallerSha256: A13ACE27E46F6BD0786C6DD54E4069C9AACECB7C301E87F3DFE9F99240DBC368
- Architecture: arm64
  InstallerUrl: https://github.com/RickStrahl/MarkdownMonsterReleases/raw/master/v3/v3.5/MarkdownMonsterSetup-3.5.14.exe
  InstallerSha256: A13ACE27E46F6BD0786C6DD54E4069C9AACECB7C301E87F3DFE9F99240DBC368
ManifestType: installer
ManifestVersion: 1.6.0
